# Site settings
title: Jekyll Blog
name: My Blog
email: myemail@here.com
description: > # this means to ignore newlines until "baseurl:"
  Experimenting with Jekyll. Let's see what I can do. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#!# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
#!# twitter_username: jekyllrb
#!# github_username:  jekyll
#!# paginate: 10

# Build settings
#!# markdown: kramdown
markdown: rdiscount
permalink: pretty
